# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

sitename: Wood Concepts
email: woodconceptsnz@gmail.com
phone: 027 341 3409
address: >-
  <b>Reclaimed Timber Traders</b><br/>
  50 Tip Road <br/>
  Palmerston North 4412 

description: >- # this means to ignore newlines until "baseurl:"
  We carefully craft bespoke woodwork creations from reclaimed New Zealand native timber and other timber from elsewhere.
  With innovative craftsmanship, we create beautiful woodwork using traditional joinery methods tailored to suit your unique style and space.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://woodconcepts.nz" # the base hostname & protocol for your site, e.g. http://example.com
lang: en-NZ
logoimgsrc: /assets/logo.png
copyright: All rights reserved &#169; 2024 Woodconcepts. Web design by <a href="https://pukekocode.nz">pukekocode.nz</a>

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
remote-theme: electrictangent/woodconcepts-theme

defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo.png
      

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
